Imports LogiParkLib.DBConnection
Namespace LogiParkObjects
    ''' <summary>
    ''' @Project/Product Name:  SAS :: Terminal Management System 
    ''' @Version	: Version 1.0
    ''' @Module/Class Name	: SubRouteMaster Class
    ''' @author	: Santosh Singh- 17/8/2011
    ''' </summary>
    ''' <remarks> </remarks>
    Public Class ExtSubRouteMaster
        Inherits SubRouteMaster


    End Class

End Namespace
